.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. globalboost_qt test_globalboost_qt
clean: FORCE
	$(MAKE) -C .. globalboost_qt_clean test_globalboost_qt_clean
check: FORCE
	$(MAKE) -C .. test_globalboost_qt_check
globalboost-qt globalboost-qt.exe: FORCE
	 $(MAKE) -C .. globalboost_qt
apk: FORCE
	$(MAKE) -C .. globalboost_qt_apk
